"""
Module Name: graveyard_rag
Purpose: Retain the mathematical reasoning of failed paths to prevent AI from looping endlessly on identical mistakes.
Responsibilities:
  - Interface via SQLite proxy for vector matching (Upgradeable to ChromaDB).
  - Store AST fingerprints and the formal failure output reasons from Lean 4.
  - Query memory before evaluating a new path via localized cosine thresholding.
Dependencies: sqlite3, json, math
Input: Float vectors generated by an embedding model.
Output: Lists of prior failed attempts that match current strategies.
Possible Errors: Dimensionality mismatch, disk corruption.
Testing Method: Inserting mocked multidimensional arrays and verifying cosine distances.
Estimated Complexity: Medium.
Integration Notes: Call `query_graveyard()` before submitting *any* AST to the compiler.
"""
import sqlite3
import json
import math
import struct
from typing import Dict, List, Optional
from contextlib import contextmanager
from src.core.sys_logger import get_logger

logger = get_logger("GraveyardMemory")

class GraveyardDB:
    def __init__(self, db_path: str = "truemath_graveyard.db"):
        self.db_path = db_path
        self._vector_cache: List[tuple] = []  # In-memory cache of (ast_hash, failure_reason, unpacked_vector)
        self._initialize_db()
        self._load_vector_cache()

    @contextmanager
    def _get_connection(self):
        """Helper to create SQLite connections with WAL and optimization PRAGMAs, ensuring clean closure."""
        conn = sqlite3.connect(self.db_path, timeout=15.0)
        conn.execute("PRAGMA journal_mode = WAL")
        conn.execute("PRAGMA synchronous = NORMAL")
        try:
            yield conn
        finally:
            conn.close()

    def _initialize_db(self) -> None:
        """Initializes the database schema for the RAG Graveyard."""
        try:
            with self._get_connection() as conn:
                cursor = conn.cursor()
                cursor.execute('''
                    CREATE TABLE IF NOT EXISTS failure_memory (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        ast_hash TEXT NOT NULL,
                        failure_reason TEXT NOT NULL,
                        pseudo_vector BLOB NOT NULL
                    )
                ''')
                cursor.execute('CREATE INDEX IF NOT EXISTS idx_hash ON failure_memory(ast_hash)')
                conn.commit()
            logger.info(f"Graveyard Analytics Store initialized at {self.db_path}")
        except sqlite3.Error as e:
            logger.error(f"Graveyard DB init failed critically: {e}")
            raise

    def _load_vector_cache(self) -> None:
        """Pre-loads vectors from DB into memory cache to allow ultra-fast RAG scans."""
        try:
            with self._get_connection() as conn:
                cursor = conn.cursor()
                # Limit to 5000 to prevent OOM
                cursor.execute("SELECT ast_hash, failure_reason, pseudo_vector FROM failure_memory ORDER BY id DESC LIMIT 5000")
                for row in cursor.fetchall():
                    ast_hash, reason, binary_vector = row
                    vector_length = len(binary_vector) // 4
                    db_vector = struct.unpack(f'{vector_length}f', binary_vector)
                    db_mag = math.sqrt(sum(a * a for a in db_vector))
                    self._vector_cache.append((ast_hash, reason, db_vector, db_mag))
            logger.info(f"Graveyard semantic cache pre-warmed with {len(self._vector_cache)} vector records.")
        except Exception as e:
            logger.error(f"Failed to bootstrap graveyard vector cache: {e}", exc_info=True)
            
    def bury_path(self, ast_hash: str, failure_reason: str, vector: List[float]) -> bool:
        """Stores a structurally failed path into the mathematical graveyard for future reference."""
        try:
            with self._get_connection() as conn:
                # C-level conversion to pure byte streams, saving ~70% db size vs JSON strings
                binary_vector = struct.pack(f'{len(vector)}f', *vector)
                cursor = conn.cursor()
                cursor.execute(
                    "INSERT INTO failure_memory (ast_hash, failure_reason, pseudo_vector) VALUES (?, ?, ?)",
                    (ast_hash, failure_reason, binary_vector)
                )
                conn.commit()
            
            # Commit to fast RAM cache too with pre-calculated magnitude
            db_mag = math.sqrt(sum(a * a for a in vector))
            self._vector_cache.append((ast_hash, failure_reason, tuple(vector), db_mag))
            if len(self._vector_cache) > 5000:
                self._vector_cache.pop(0)

            logger.debug(f"Buried path `{ast_hash}` in Graveyard.")
            return True
        except Exception as e:
            logger.error(f"Failed to bury path {ast_hash}: {e}", exc_info=True)
            return False

    def query_graveyard(self, query_vector: List[float], threshold: float = 0.95) -> List[Dict]:
        """
        Queries the Graveyard returning paths and their reasons that match closely to the current theoretical path.
        Extremely useful for pruning MCTS trees locally.
        """
        matches = []
        try:
            # Query the in-memory cache directly! Eliminates DB lookups and on-the-fly binary unpacking.
            # Precompute query magnitude once, preventing 5,000 redundant sqrt/sum loops
            q_mag = math.sqrt(sum(a * a for a in query_vector))
            if q_mag == 0:
                return []
                
            for ast_hash, reason, db_vector, db_mag in self._vector_cache:
                # Performance & Correctness Optimization: Verify dimensionality spaces match
                # Prevents incorrect distance outputs or index errors on partial/corrupted query shapes.
                if len(db_vector) != len(query_vector):
                    continue
                if db_mag == 0:
                    continue
                # Inline cosine similarity for maximum performance
                dot_product = sum(a * b for a, b in zip(query_vector, db_vector))
                sim = dot_product / (q_mag * db_mag)
                if sim >= threshold:
                    matches.append({'ast_hash': ast_hash, 'reason': reason, 'similarity': sim})
        except Exception as e:
            logger.error(f"Graveyard semantic query failed: {e}", exc_info=True)
            
        # Sort so the highest matching logical failure is the first returned.
        return sorted(matches, key=lambda x: x['similarity'], reverse=True)
