"""
Module Name: crypto_math
Purpose: Real cryptography-adjacent math for coding/educational use —
         integer factoring, discrete logarithm (small cases), and RSA
         building blocks. Uses the same real algorithms (Pollard's rho,
         baby-step giant-step, modular exponentiation) that underpin actual
         cryptanalysis coursework.
Responsibilities:
  - factor_integer: full factorization (delegates to number_theory).
  - discrete_log_bsgs: baby-step giant-step discrete log solver (feasible
    for moduli up to roughly 10^12 in reasonable time; real-world discrete
    log for cryptographic-size primes, e.g. 2048-bit, is intractable by
    design — that's WHY it's used in cryptography).
  - rsa_toy_keygen: generates a SMALL (educational-size, e.g. 16-24 bit)
    RSA keypair to demonstrate the math end-to-end. NEVER use this for
    anything actually needing security — real RSA needs 2048+ bit primes.
Dependencies: math, random
Honesty note: This module deliberately does NOT and cannot break real
              cryptography — factoring/discrete-log are only fast here
              because the numbers are small by design. That gap (small
              numbers = fast, cryptographic-size numbers = computationally
              infeasible) is precisely the security assumption RSA/Diffie-
              Hellman rely on.
"""
from __future__ import annotations

import math
import random

from src.math_engine.number_theory import is_prime, mod_inverse, mod_pow, prime_factors


def factor_integer(n: int) -> dict:
    factors = prime_factors(n)
    return {"n": n, "prime_factors": factors, "is_prime": len(factors) == 1}


def discrete_log_bsgs(g: int, h: int, p: int) -> dict:
    """Baby-step giant-step: solves g^x ≡ h (mod p) for x, in O(sqrt(p))
    time/space. Practical for p up to roughly 10^12; this is the same
    fundamental algorithm (with cryptographic-size primes, infeasible in
    practice) that makes Diffie-Hellman secure at real key sizes."""
    if p > 10**14:
        return {
            "status": "error",
            "message": "Modulus too large for baby-step giant-step in a reasonable time "
                       "(this is exactly why discrete log is hard at cryptographic sizes).",
        }
    m = math.isqrt(p) + 1

    table = {}
    e = 1
    for j in range(m):
        table.setdefault(e, j)
        e = (e * g) % p

    g_inv_m = mod_inverse(pow(g, m, p), p)
    if g_inv_m is None:
        return {"status": "error", "message": "g has no inverse mod p — check that gcd(g, p) = 1."}

    gamma = h % p
    for i in range(m):
        if gamma in table:
            x = i * m + table[gamma]
            return {"status": "ok", "x": x, "verification": f"{g}^{x} mod {p} = {pow(g, x, p)} (should equal {h % p})"}
        gamma = (gamma * g_inv_m) % p

    return {"status": "ok", "found": False, "message": "No solution found (h may not be in the subgroup generated by g)."}


def _random_prime(bits: int) -> int:
    while True:
        candidate = random.getrandbits(bits) | (1 << (bits - 1)) | 1
        if is_prime(candidate):
            return candidate


def rsa_toy_keygen(bits: int = 16) -> dict:
    """Generates a SMALL, educational-only RSA keypair (default 16-bit
    primes) so you can see the full RSA math (n, e, d, encrypt, decrypt) end
    to end. This is deliberately toy-sized for demonstration/coding-practice
    — it provides ZERO real security. Real RSA uses 1024-2048+ bit primes."""
    bits = max(8, min(bits, 24))  # hard cap — this is for demonstration, not real use
    p = _random_prime(bits)
    q = _random_prime(bits)
    while q == p:
        q = _random_prime(bits)

    n = p * q
    phi = (p - 1) * (q - 1)
    e = 65537 if 65537 < phi and math.gcd(65537, phi) == 1 else 3
    while math.gcd(e, phi) != 1:
        e += 2
    d = mod_inverse(e, phi)

    return {
        "status": "ok",
        "p": p, "q": q, "n": n, "phi": phi,
        "public_key": {"e": e, "n": n},
        "private_key": {"d": d, "n": n},
        "warning": f"Toy-sized ({bits}-bit primes) — for learning the math only, NOT secure. Real RSA needs 1024+ bit primes.",
    }


def rsa_encrypt(message_int: int, e: int, n: int) -> int:
    if message_int >= n:
        raise ValueError(f"Message ({message_int}) must be smaller than n ({n}) for this simple scheme.")
    return mod_pow(message_int, e, n)


def rsa_decrypt(cipher_int: int, d: int, n: int) -> int:
    return mod_pow(cipher_int, d, n)
